### ISSUE TITLE
RyeCharm throws exception when opening existing project in PyCharm 2024.3.1

### ISSUE THREAD

**Issue by Dragonrun1** [InSyncWithFoo/ryecharm#36]
### What happened?

Just updated to latest PyCharm community version and tried to open project and get IDE Internal Error.

Linux Mint 22 Wilma

### Steps to reproduce

Open an existing project.

### Relevant log output or stack trace

```text
com.intellij.diagnostic.PluginException: Cannot load class insyncwithfoo.ryecharm.uv.managing.UVPackageManager (
  error: class insyncwithfoo.ryecharm.uv.managing.UVPackageManager overrides final method com.jetbrains.python.packaging.management.PythonPackageManager.installPackage-0E7RQCE(Lcom/jetbrains/python/packaging/common/PythonPackageSpecification;Ljava/util/List;Lkotli,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=RyeCharm, id=insyncwithfoo.ryecharm, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/PyCharmCE2024.3/ryecharm, version=0.1.0-alpha-4, package=null, isBundled=false), packagePrefix=null, state=active, parents=PluginDescriptor(name=Toml, id=org.toml.lang, moduleName=intellij.toml.json, descriptorPath=intellij.toml.json.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/toml, version=243.22562.180, package=org.toml.ide.json, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal.sh, descriptorPath=intellij.terminal.sh.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/terminal, version=243.22562.180, package=org.jetbrains.plugins.terminal.sh, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, moduleName=intellij.terminal/cloud, descriptorPath=intellij.terminal.cloud.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/terminal, version=243.22562.180, package=org.jetbrains.plugins.terminal.cloud, isBundled=true), PluginDescriptor(name=Toml, id=org.toml.lang, moduleName=intellij.toml.grazie, descriptorPath=intellij.toml.grazie.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/toml, version=243.22562.180, package=com.intellij.toml.grazie, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.terminal, descriptorPath=intellij.python.terminal.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.terminal, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.markdown, descriptorPath=intellij.python.markdown.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.markdown, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.langInjection, descriptorPath=intellij.python.langInjection.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.langInjection, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.grazie, descriptorPath=intellij.python.grazie.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.grazie, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.featuresTrainer, descriptorPath=intellij.python.featuresTrainer.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.featuresTrainer, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.copyright, descriptorPath=intellij.python.copyright.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.copyright, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minorRider, descriptorPath=intellij.python.community.plugin.minorRider.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.plugin.minorRider, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.minor, descriptorPath=intellij.python.community.plugin.minor.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.plugin.minor, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.java, descriptorPath=intellij.python.community.plugin.java.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.plugin.java, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.plugin.impl, descriptorPath=intellij.python.community.plugin.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.plugin.impl, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.impl.huggingFace, descriptorPath=intellij.python.community.impl.huggingFace.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.impl.huggingFace, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.python.community.communityOnly, descriptorPath=intellij.python.community.communityOnly.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.python.community.communityOnly, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, moduleName=intellij.commandInterface, descriptorPath=intellij.commandInterface.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.intellij.commandInterface, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.impl, descriptorPath=intellij.platform.vcs.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.log.impl, descriptorPath=intellij.platform.vcs.log.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.vcs.dvcs.impl, descriptorPath=intellij.platform.vcs.dvcs.impl.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=IDEA CORE, id=com.intellij, moduleName=intellij.platform.collaborationTools, descriptorPath=intellij.platform.collaborationTools.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/lib, version=243.22562.180, package=null, isBundled=true), PluginDescriptor(name=Toml, id=org.toml.lang, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/toml, version=243.22562.180, package=org.toml, isBundled=true), PluginDescriptor(name=Terminal, id=org.jetbrains.plugins.terminal, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/terminal, version=243.22562.180, package=org.jetbrains.plugins.terminal, isBundled=true), PluginDescriptor(name=Python Community Edition, id=PythonCore, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/Toolbox/apps/pycharm-community/plugins/python-ce, version=243.22562.180, package=com.jetbrains.python, isBundled=true), )
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:333)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.kt:179)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:152)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at insyncwithfoo.ryecharm.uv.managing.UVPackageManagerProvider.createPackageManagerForSdk(UVPackageManagerProvider.kt:28)
	at com.jetbrains.python.packaging.common.PackageManagerHolder.forSdk$lambda$1(util.kt:42)
	at com.jetbrains.python.packaging.common.PackageManagerHolder.forSdk$lambda$2(util.kt:40)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.jetbrains.python.packaging.common.PackageManagerHolder.forSdk(util.kt:40)
	at com.jetbrains.python.packaging.management.PythonPackageManager$Companion.forSdk(PythonPackageManager.kt:59)
	at com.jetbrains.python.sdk.PythonSdkUpdater$PyUpdateSdkTask.refreshPackages(PythonSdkUpdater.java:186)
	at com.jetbrains.python.sdk.PythonSdkUpdater$PyUpdateSdkTask.run(PythonSdkUpdater.java:153)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IncompatibleClassChangeError: class insyncwithfoo.ryecharm.uv.managing.UVPackageManager overrides final method com.jetbrains.python.packaging.management.PythonPackageManager.installPackage-0E7RQCE(Lcom/jetbrains/python/packaging/common/PythonPackageSpecification;Ljava/util/List;Lkotli
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1118)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:303)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:115)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:58)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:240)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:190)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.kt:328)
	... 41 more
```

### Operating system

Linux

**Comment by Dragonrun1** [comment]
When I looked at the Exception I figured they'd changed something on you to break things just not that much of a Java guy to dig any deeper. I only recently started working on some personal python projects and have been learning about dev tools people are using and when I run across ruff and then uv and saw they are rust based had to try them :) Good experience so far this was the first thing that was not great and out of your control so do keep up the good work.

**Comment by Dragonrun1** [comment]
When do you expect this to be in marketplace?
